steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nextjs-cloudrun-demo:$COMMIT_SHA', '.' ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nextjs-cloudrun-demo:$COMMIT_SHA' ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - nextjs-cloudrun-demo
      - --image
      - asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nextjs-cloudrun-demo:$COMMIT_SHA
      - --region
      - asia-south1
      - --platform
      - managed
      - --allow-unauthenticated
      # Uncomment if using secrets:
      # - --set-secrets=MY_API_KEY=MY_API_KEY:latest

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/nextjs-cloudrun-demo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
