steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/nextjs-demo-project-467006/cloudrun-apps/nextjs-cloudrun-demo:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/nextjs-demo-project-467006/cloudrun-apps/nextjs-cloudrun-demo:$SHORT_SHA'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'nextjs-cloudrun-demo',
        '--image',
        'us-central1-docker.pkg.dev/nextjs-demo-project-467006/cloudrun-apps/nextjs-cloudrun-demo:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080',
        '--service-account',
        'nextjs-deployer@nextjs-demo-project-467006.iam.gserviceaccount.com'
      ]

images:
  - 'us-central1-docker.pkg.dev/nextjs-demo-project-467006/cloudrun-apps/nextjs-cloudrun-demo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
